//! Compile community scenes from ~/.config/termpaper/marketplace.toml into
//! OUT_DIR/marketplace.rs so `cargo install` picks up installed packages.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug)]
struct InstalledScene {
    scene_name: String,
    struct_name: String,
    description: String,
    themes: Vec<String>,
    install_path: PathBuf,
}

fn config_path() -> PathBuf {
    if let Ok(xdg) = env::var("XDG_CONFIG_HOME") {
        if !xdg.is_empty() {
            return PathBuf::from(xdg).join("termpaper/marketplace.toml");
        }
    }
    if let Ok(home) = env::var("HOME") {
        return PathBuf::from(home).join(".config/termpaper/marketplace.toml");
    }
    PathBuf::from("/dev/null")
}

fn parse_installed(raw: &str) -> Vec<InstalledScene> {
    #[derive(serde::Deserialize)]
    struct Root {
        #[serde(default)]
        installed: Vec<Entry>,
    }
    #[derive(serde::Deserialize)]
    struct Entry {
        scene_name: String,
        #[serde(default)]
        struct_name: Option<String>,
        description: String,
        #[serde(default)]
        themes: Vec<String>,
        install_path: String,
    }

    let root: Root = match toml::from_str(raw) {
        Ok(r) => r,
        Err(_) => return Vec::new(),
    };
    root.installed
        .into_iter()
        .filter_map(|e| {
            let install_path = PathBuf::from(&e.install_path);
            if !install_path.join("scene.rs").is_file() {
                return None;
            }
            let struct_name = e.struct_name.unwrap_or_else(|| {
                let mut s = e.scene_name.clone();
                if let Some(r) = s.get_mut(0..1) {
                    r.make_ascii_uppercase();
                }
                s
            });
            Some(InstalledScene {
                scene_name: e.scene_name,
                struct_name,
                description: e.description,
                themes: if e.themes.is_empty() {
                    vec!["classic".into()]
                } else {
                    e.themes
                },
                install_path,
            })
        })
        .collect()
}

fn load_installed() -> Vec<InstalledScene> {
    let path = config_path();
    println!("cargo:rerun-if-changed={}", path.display());
    let Ok(raw) = fs::read_to_string(&path) else {
        return Vec::new();
    };
    parse_installed(&raw)
}

fn write_marketplace(out_dir: &Path, installed: &[InstalledScene]) {
    let mut modules = String::new();
    let mut create_arms = String::new();
    let mut theme_arms = String::new();
    let mut scene_rows = String::new();

    for (i, entry) in installed.iter().enumerate() {
        let mod_name = format!("mp_{i}");
        let src = entry.install_path.join("scene.rs");
        let dest = out_dir.join(format!("{mod_name}.rs"));
        if fs::copy(&src, &dest).is_err() {
            continue;
        }
        println!("cargo:rerun-if-changed={}", src.display());

        modules.push_str(&format!("#[path = \"{mod_name}.rs\"]\nmod {mod_name};\n\n"));
        create_arms.push_str(&format!(
            "        \"{}\" => Some(Box::new({mod_name}::{}::new(rng, theme, d))),\n",
            entry.scene_name, entry.struct_name
        ));
        let theme_list = entry
            .themes
            .iter()
            .map(|t| format!("\"{t}\""))
            .collect::<Vec<_>>()
            .join(", ");
        theme_arms.push_str(&format!(
            "        \"{}\" => Some(&[{theme_list}]),\n",
            entry.scene_name
        ));
        let desc = entry.description.replace('"', "\\\"");
        scene_rows.push_str(&format!(
            "    (\"{}\", \"{desc} [community]\"),\n",
            entry.scene_name
        ));
    }

    let body = format!(
        r#"// @generated by build.rs — do not edit
{modules}
pub const MARKETPLACE_SCENES: &[(&str, &str)] = &[
{scene_rows}];

pub fn marketplace_create(
    name: &str,
    opts: &SceneOptions,
    rng: rand::rngs::StdRng,
) -> Option<Box<dyn Scene>> {{
    let theme = opts.theme.as_deref();
    let d = opts.detail;
    match name {{
{create_arms}        _ => None,
    }}
}}

pub fn marketplace_themes(name: &str) -> Option<&'static [&'static str]> {{
    match name {{
{theme_arms}        _ => None,
    }}
}}
"#
    );
    fs::write(out_dir.join("marketplace.rs"), body).expect("write marketplace.rs");
}

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let installed = load_installed();
    write_marketplace(&out_dir, &installed);
}
