//! Generates the Studio shader-scene registry.
//!
//! Every `src/gpu/scenes/*.wgsl` file is a scene; its `//!` header is parsed
//! with the same parser the runtime uses (`src/scene/shader_meta.rs`) and
//! emitted as a `ShaderSpec` row. Adding a scene is adding a file — nobody
//! edits a shared registry, so scenes can be written in parallel.

#[path = "src/scene/shader_meta.rs"]
#[allow(dead_code)]
mod shader_meta;

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn wgsl_files(dir: &Path) -> Vec<PathBuf> {
    let mut v: Vec<PathBuf> = std::fs::read_dir(dir)
        .map(|rd| {
            rd.filter_map(|e| e.ok().map(|e| e.path()))
                .filter(|p| p.extension().is_some_and(|x| x == "wgsl"))
                .collect()
        })
        .unwrap_or_default();
    v.sort();
    v
}

fn main() {
    let root = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let scenes_dir = root.join("src/gpu/scenes");
    let lib_dir = scenes_dir.join("lib");
    let entry = root.join("src/gpu/shaders/scene_entry.wgsl");
    println!("cargo:rerun-if-changed=src/gpu/scenes");
    println!("cargo:rerun-if-changed=src/gpu/scenes/lib");
    println!("cargo:rerun-if-changed=src/gpu/shaders/scene_entry.wgsl");
    println!("cargo:rerun-if-changed=src/scene/shader_meta.rs");

    let mut metas = Vec::new();
    for p in wgsl_files(&scenes_dir) {
        println!("cargo:rerun-if-changed={}", p.display());
        let text = std::fs::read_to_string(&p).unwrap();
        let stem = p.file_stem().unwrap().to_str().unwrap().to_string();
        match shader_meta::parse(&text, &stem) {
            Ok(m) => metas.push((p, m)),
            Err((line, msg)) => panic!("{}:{line}: {msg}", p.display()),
        }
    }
    if let Err(e) = shader_meta::validate_set(&metas.iter().map(|m| m.1.clone()).collect::<Vec<_>>()) {
        panic!("{e}");
    }
    metas.sort_by(|a, b| (a.1.category_rank(), &a.1.name).cmp(&(b.1.category_rank(), &b.1.name)));

    let q = |s: &str| format!("{s:?}");
    let list = |v: &[String]| format!("&[{}]", v.iter().map(|s| q(s)).collect::<Vec<_>>().join(", "));
    let mut out = String::new();
    out.push_str("// @generated by build.rs from src/gpu/scenes — do not edit.\n");

    // library modules, in canonical order
    out.push_str("pub static LIB: &[LibModule] = &[\n");
    for (name, _) in shader_meta::MODULES {
        let path = lib_dir.join(format!("{name}.wgsl"));
        if !path.exists() {
            panic!("missing shader library module {}", path.display());
        }
        println!("cargo:rerun-if-changed={}", path.display());
        writeln!(
            out,
            "    LibModule {{ name: {}, source: include_str!({}) }},",
            q(name),
            q(path.to_str().unwrap())
        )
        .unwrap();
    }
    out.push_str("];\n");
    writeln!(out, "pub const ENTRY: &str = include_str!({});", q(entry.to_str().unwrap())).unwrap();

    out.push_str("pub static SHADER_SCENES: &[ShaderSpec] = &[\n");
    for (path, m) in &metas {
        let cat = {
            let mut c = m.category.clone();
            c[..1].make_ascii_uppercase();
            c
        };
        let cost = {
            let mut c = m.cost.clone();
            c[..1].make_ascii_uppercase();
            c
        };
        writeln!(
            out,
            "    ShaderSpec {{ name: {}, title: {}, category: Category::{cat}, tags: {}, desc: {}, \
             themes: {}, uses: &[{}], cost: Cost::{cost}, tonemap: {}, exposure: {:?}, \
             ss_manual: {}, fallback: {}, credits: {}, source: include_str!({}), \
             path: {} }},",
            q(&m.name),
            q(&m.title),
            list(&m.tags),
            q(&m.desc),
            list(&m.themes),
            m.uses.iter().map(|u| q(u)).collect::<Vec<_>>().join(", "),
            m.tonemap_mode(),
            m.exposure,
            m.ss_manual,
            q(&m.fallback),
            q(&m.credits),
            q(path.to_str().unwrap()),
            q(&format!("src/gpu/scenes/{}.wgsl", m.name)),
        )
        .unwrap();
    }
    out.push_str("];\n");

    let dest = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("shader_scenes.rs");
    std::fs::write(dest, out).unwrap();
}
