#!/usr/bin/env bash
# Build and install termpaper from the local repo tree (no git tag required).
set -euo pipefail

arch_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$arch_dir/../.." && pwd)"
ver="$(sed -n 's/^version = "\(.*\)"/\1/p' "$root/Cargo.toml" | head -1)"
[[ -n "$ver" ]] || { echo "could not read version from Cargo.toml" >&2; exit 1; }

staging="$(mktemp -d)"
trap 'rm -rf "$staging"' EXIT

info() { printf '==> %s\n' "$*"; }

info "packaging termpaper $ver from $root"
mkdir -p "$staging/termpaper-$ver"
rsync -a \
    --exclude target \
    --exclude .git \
    --exclude packaging/arch/termpaper-*.tar.gz \
    "$root/" "$staging/termpaper-$ver/"

tarball="$arch_dir/termpaper-$ver.tar.gz"
tar -C "$staging" -czf "$tarball" "termpaper-$ver"

cat >"$arch_dir/PKGBUILD.local" <<EOF
# Generated by build-local.sh — do not commit.
pkgname=termpaper
pkgver=$ver
pkgrel=1
pkgdesc="Wallpaper Engine for the terminal — animated truecolor scenes"
arch=('x86_64' 'aarch64')
url="https://github.com/Aphrodine-wq/termpaper"
license=('MIT')
depends=()
makedepends=('cargo')
options=('!strip')
source=("\$(basename "$tarball")")
sha256sums=('SKIP')

build() {
    cd "termpaper-$pkgver"
    cargo build --release --locked
}

check() {
    cd "termpaper-$pkgver"
    cargo test --lib --locked
}

package() {
    cd "termpaper-$pkgver"
    install -Dm755 target/release/termpaper "\$pkgdir/usr/bin/termpaper"
    install -Dm644 README.md "\$pkgdir/usr/share/doc/termpaper/README.md"
    install -Dm644 LICENSE "\$pkgdir/usr/share/licenses/termpaper/LICENSE"
}
EOF

info "running makepkg -si"
cd "$arch_dir"
makepkg -p PKGBUILD.local -si
